automower_ble/protocol: Only decode gatt chars if we read them
To avoid errors like

```
AttributeError: 'NoneType' object has no attribute 'decode'
```

we only decode the data when we read it instead of at the function
return. This should avoid errors if we can't read it.

Resolves: https://github.com/home-assistant/core/issues/143827
Signed-off-by: Alistair Francis <alistair@alistair23.me>